from ejercicio2 import random_generator

def capicua(arr):
  
  length = len(arr)
  reversedArr = []

  for x in range(length -1, -1, -1):
    reversedArr.append(arr[x])
  
  print(arr)
  print(reversedArr)

  if(arr == reversedArr):
    print('The array is "capicua"')
  else:
    print('The array is not "capicua"')

capicua(random_generator(0, 6, 5))

"""
Explanaiton: 

1) First of all, we have to import the random array generator's function form exercise 2.
2) For this program, we declare a function which receives an array (generated by exercise 2' function) as argument
3) Declare an empty array to store the reversed array so we can compare each other
4) With a 'For Loop' we iterate from the last element of the array to the first one
5) In each iteration, we push the value to the empty array previously declared
6) Once we finished the iteration and we have the reversed array, we want to compare and know if they are equal
7) With an 'If else' statement, we can validate if the main array is equal to the reversed one. This means that if we read the array from left to right or from right to left is the same
8) Finally, we print an answer depending of the validation
"""